---
title: "Depression and Abstract and Concrete Language"
author: 
  - name: "Lihi"
  - name: "Lilach"
  - name: "Noga"
  - name: "Yonatan M"
format:
  pdf:
    template: apa7
    number-sections: true
    toc: true
    fig-cap-location: top
    reference-location: margin
execute: 
  warning: false
  message: false
editor: visual
embed-resources: true
---

# **The Effect of Depression Identity Claims on Abstract and Concrete Language Use Across Two Social Media Platforms:**

## Literature Review

Language use can be categorized by distinguishing between abstract and concrete expressions (Tater et al., 2022). Concrete language includes words and concepts that are directly experienced through the five senses—sight, hearing, touch, taste, and smell (e.g., chocolate, shirt). In contrast, abstract language encompasses intangible concepts or experiences that are not readily perceived through the senses, such as "justice" or "depression". Previous research indicates that individuals diagnosed with depression exhibit distinct language patterns compared to control groups. Specifically, depressed individuals frequently use more past-tense verbs, show reduced use of future-oriented language (Trifu et al., 2024), and more commonly employ absolute terms such as "always" (Al-Mosaiwi & Johnstone, 2018). Depression has also been linked to increased use of first-person singular pronouns (e.g., “I,” “my”) and negatively valenced emotion words (Edwards & Holtzman, 2017; Eichstaedt et al., 2018). Further evidence suggests that depressed individuals tend to employ more abstract thinking. Depression is associated with abstract, overgeneralized thought patterns (Beck, 1976) and ruminative tendencies (Nolen-Hoeksema, 1991), both of which are likely reflected in more abstract linguistic usage. Additionally, concreteness training has been shown to alleviate depressive symptoms (Watkins et al., 2009), which suggests that abstract thinking plays a role in the maintenance of depression. However, to our knowledge, no prior study has examined whether the abstract thinking characteristic of depressed individuals is also reflected in social media text. In our study, we aim to investigate whether self-identified depressed individuals (refers to users who explicitly disclose a depression diagnosis) use more abstract language than non-depressed controls. We hypothesize that self-identified depressed individuals will exhibit greater use of abstract language compared to the control group. We will test this hypothesis by applying NLP methods to analyze and compare abstract versus concrete language usage between depressed individuals and a control group. We plan to collect tweets and Reddit posts from both groups and rate their content based on abstractness-concreteness levels. We will use the two different platforms to validate our findings and assess the robustness of the results.

## **Datasets:**

As previously noted, the two datasets used in our study are sourced from different social media platforms: Twitter (also known as X) and Reddit. The Twitter dataset contains 20,000 tweets, half of which were written by users who were classified as experiencing depression (Infamous Coder, n.d.). Although the data appears to be balanced at first glance, a closer examination reveals that these tweets were produced by 72 users - 54 classified as depressed and just 18 as non-depressed. This might pose a potential limitation, as 18 non-depressed users may not adequately represent the broader population of non-depressed, particularly when exploring linguistic variability related to concreteness-abstractness. In other words, the small sample of non-depressed users may not capture the heterogeneity in language use that exists within the population. A second limitation is inherent to Twitter as a platform and is especially relevant in our context. Due to Twitter's character limit, tweets tend to be brief, which may constrain the depth of self-expression and hinder the ability to convey complex experiences (Teitelbaum & Simchon, 2024). As a result, the use of abstract language, which often requires elaboration may be restricted. Nonetheless, this dataset offers several notable advantages. First, because each participant contributes multiple tweets, the data is hierarchically structured. This nested design might allow us to perform more sophisticated analyses, such as examining whether a user’s level of concreteness or abstractness changes over time, and whether this variation is associated with a depression. Second, the dataset includes additional user-level variables such as number of followers and friends, which may influence or correlate with language use. Thus, we might want to control them in our analysis. Our Reddit dataset is composed of two original datasets (Low et al., 2020), each extracted from different Reddit communities. Specifically, one dataset includes posts from communities related to depression, while the other includes posts from communities centered around relationships. In our future analysis, we will refer to the former as the depression group and the latter as the control group. This combined dataset presents several limitations. First, we chose the community that serves as control group, and this selection may influence the results. Specifically, the nature of a community's content may shape the type of language its users typically employ. That is, the level of concreteness or abstractness in posts can vary substantially across different communities. For instance, a community centered on pizza lovers might foster more concrete language use than one focused on romantic or interpersonal relationships. This difference in baseline of concreteness-abstractness may confound our attempts to isolate the effects of depression on language use. A second limitation is our inability to confirm the mental health status of users in the control group. Users participating in relationship discussions may still experience symptoms of depression or other emotional difficulties. As a result, the assumption that this group is "non-depressed" may not hold. Moreover, there may be overlap in membership between depression-related and relationship-related subreddits, further blurring group distinctions. Despite these limitations, the dataset offers several important strengths. The dataset includes a wide range of features, much more than the dataset of Twitter. These features might enable us to both control for potential confounding variables and explore the relationship between depression and concreteness-abstractness more precisely. Additionally, the dataset is relatively large, as it contains over 20,000 posts in the depression group alone. Therefore, we can easily divide the data into training, validation, and test sets, facilitating model selection and ensuring performance can be assessed on unseen data.

**References** Al-Mosaiwi, M., & Johnstone, T. (2018). Linguistic markers of moderate and absolute natural language. Personality and Individual Differences, 134, 119–124. https://doi.org/10.1016/j.paid.2018.06.004 Beck, A. T. (1976). Cognitive therapy and the emotional disorders. International Universities Press. Edwards, T., & Holtzman, N. S. (2017). A meta-analysis of correlations between depression and first person singular pronoun use. Journal of Research in Personality, 68, 63–68. https://doi.org/10.1016/j.jrp.2017.02.005 Eichstaedt, J. C., Smith, R. J., Merchant, R. M., Ungar, L. H., Crutchley, P., Preoţiuc-Pietro, D., Asch, D. A., & Schwartz, H. A. (2018). Facebook language predicts depression in medical records. Proceedings of the National Academy of Sciences, 115(44), 11203–11208. https://doi.org/10.1073/pnas.1802331115 infamouscoder. (n.d.). Mental health social media \[Data set\]. Kaggle. https://www.kaggle.com/datasets/infamouscoder/mental-health-social-media Kauschke, C., Mueller, N., Kircher, T., & Nagels, A. (2018). Do Patients With Depression Prefer Literal or Metaphorical Expressions for Internal States? Evidence From Sentence Completion and Elicited Production. Frontiers in Psychology, 9. https://doi.org/10.3389/fpsyg.2018.01326 Low, D. M., Rumker, L., Torous, J., Cecchi, G., Ghosh, S. S., & Talkar, T. (2020). Reddit Mental Health Dataset \[Data set\]. Zenodo. https://doi.org/10.17605/OSF.IO/7PEYQ Nolen-Hoeksema, S. (1991). Responses to depression and their effects on the duration of depressive episodes. Journal of Abnormal Psychology, 100(4), 569–582. https://doi.org/10.1037/0021-843x.100.4.569 Tater, T., Frassinelli, D., & Schulte, S. (2022). Concreteness vs. Abstractness: A Selectional Preference Perspective. 92–98. https://doi.org/10.18653/v1/2022.aacl-srw.13 Teitelbaum, L., & Simchon, A. (2024). Data Science for Psychology: Natural Language. https://zenodo.org/doi/10.5281/zenodo.10908366 Watkins, E. R., Baeyens, C. B., & Read, R. (2009). Concreteness training reduces dysphoria: Proof-of-principle for repeated cognitive bias modification in depression. Journal of Abnormal Psychology, 118(1), 55–64. https://doi.org/10.1037/a0013642
